url: http://prometheus-bildarchiv.de
author: prometheus
email: info@prometheus-bildarchiv.de
title: prometheus homepage
pandora_url: http://127.0.0.1:3000
engine: erb
paginate: 10
paginate_files:
- blog.de.html
- blog.en.html
pygments: true
exclude: [Rakefile]
permalink: /:year/:month/:day/:title
