---
title:    The prometheus Image Archive
title_de: Das prometheus-Bildarchiv

author:   prometheus
email:    info@prometheus-bildarchiv.de

engine:   erb
pygments: true

paginate: 10
paginate_files:
- blog/index.de.html
- blog/index.en.html

exclude:   [Rakefile]
permalink: /blog/:title

tag_page_dir:    tag
tag_page_layout: tag_page

disqus: prometheus-images
