#url: http://prometheus-bildarchiv.de
url: http://cartman.rrz.uni-koeln.de:2273
author: prometheus
email: info@prometheus-bildarchiv.de
title: The prometheus Image Archive
title_de: Das prometheus-Bildarchiv
pandora_url: http://localhost:3000
engine: erb
paginate: 10
paginate_files:
- blog/index.de.html
- blog/index.en.html
pygments: true
exclude: [Rakefile]
permalink: /post/:title
